pigeonhole: update to 0.5.11
This fixes an error in the previous package when building against recent
OpenWrt releases:

In file included from /builder/shared-workdir/build/sdk/staging_dir/target-x86_64_musl/usr/include/dovecot/lib.h:50,
                 from ext-variables-common.c:4:
ext-variables-common.c: In function 'ext_variables_load':
ext-variables-common.c:91:14: error: expected ')' before 'PRIuSIZE_T'
       "(>= %"PRIuSIZE_T" bytes)",

Signed-off-by: W. Michael Petullo <mike@flyn.org>