spoofer: Update to 1.4.0
Added PKG_USE_MIPS16 as it seems not to build under mipsel.

Error: opcode not supported on this processor: mips32r2 (mips32r2) `sync'

Signed-off-by: Rosen Penev <rosenp@gmail.com>