postgresql: fix build for ARC arch
When building for ARC the compile fails with:

  /var/lib/buildbot/slaves/dave-builder/arc_arc700/build/sdk/build_dir/target-arc_arc700_uClibc/postgresql-9.6.5/src/include/storage/s_lock.h:899:2: error: #error PostgreSQL does not have native spinlock support on this platform. To continue the compilation, rerun configure using --disable-spinlocks. However, performance will be poor. Please report this to pgsql-bugs@postgresql.org.
   #error PostgreSQL does not have native spinlock support on this platform.  To continue the compilation, rerun configure using --disable-spinlocks.  However, performance will be poor.  Please report this to pgsql-bugs@postgresql.org.

So disable spinlocks when compiling for this arch. This was done
likewise for the avr32 target, which is not supported anymore, so this
can be deleted.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>