squid: fix musl compatibility
Change `sys/signal.h` include to just `signal.h`. The build otherwise fails
due to `-Werror` with the following message:

    In file included from rfcnb-io.c:43:0:
    .../staging_dir/toolchain-mipsel_mips32_gcc-4.8-linaro_musl-1.1.10/include/sys/signal.h:1:2: error: #warning redirecting incorrect #include <sys/signal.h> to <signal.h> [-Werror=cpp]
     #warning redirecting incorrect #include <sys/signal.h> to <signal.h>
      ^
    cc1: all warnings being treated as errors

Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>