xr_usb_serial_common: fix kernel 5.4 builds
Building the xr_usb_serial module fails for Kenel 5.4 with CONFIG_PM
enabled:

xr_usb_serial_common.c:1574:15: error: 'ASYNCB_INITIALIZED' undeclared
(first use in this function); did you mean 'RCU_INITIALIZER'?

Use tty_port_initialized in order to determine the status of the TTY
port.

Signed-off-by: David Bauer <mail@david-bauer.net>
(cherry picked from commit 86e5191d99937ec705ae63c29f3576d3e30875f4)