gammu: remove nls.mk
It's causing issues with newer glib2:

../libgammu/libGammu.so.8.1.41.0: undefined reference to `libiconv'
../libgammu/libGammu.so.8.1.41.0: undefined reference to `libiconv_open'
../libgammu/libGammu.so.8.1.41.0: undefined reference to `libiconv_close'

It's because the libiconv-stub does not include a shared library that
gammu can link to.

Removed most patches since they don't seem to be needed.

Ran init script through shellcheck.

Signed-off-by: Rosen Penev <rosenp@gmail.com>