diffutils: fix fortify source compat
Compile with `-std=gnu99` instead of `-std=c99` to avoid redefining
`__attribute__` in `src/system.h`.

Fixes the following error spotted by the buildbot:

    In file included from ../lib/stdio.h:43:0,
                     from cmp.c:22:
    .../staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_musl-1.1.10_eabi/include/fortify/stdio.h: In function 'snprintf':
    .../staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_musl-1.1.10_eabi/include/fortify/stdio.h:99:2: error: invalid use of '__builtin_va_arg_pack ()'
      return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack());
      ^

Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>