neon: add back sed scripts for neon-config
Commit 6cfea32 removed the sed scripts that ran on neon-config. Now
there is build failure for Asterisk because a host include directory is
added to the build:

mips_24kc_musl/usr/lib/libintl-stub/include    -I/store/buildbot/slave/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/include/libxml2  -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations       -fPIC -DAST_MODULE=\"res_calendar_exchange\" -DAST_MODULE_SELF_SYM=__internal_res_calendar_exchange_self  -I/usr/include/neon -I/store/buildbot/slave/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/include -pthread -I/store/buildbot/slave/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/include
res_calendar_exchange.c:34:10: fatal error: ne_session.h: No such file or directory
 #include <ne_session.h>
          ^~~~~~~~~~~~~~
compilation terminated.

This commit adds back the sed scripts.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>