libmariadb: fix compilation cmake issue
This patch fixes the compilation issue of the upstream Cmake file.
If this patch is not applied we get the following compilation error output.

CMake Error at cmake/ConnectorName.cmake:30 (ENDMACRO):
  Flow control statements are not properly nested.
Call Stack (most recent call first):
  CMakeLists.txt:423 (INCLUDE)

The blamed cmake/ConnectorName.cmake file gets fixed with this patch.

Signed-off-by: Florian Eckert <fe@dev.tdt.de>
(cherry picked from commit 1e3614ba1efffb3a6b9a5927c3af90ecd79c776d)